# Generated by Django 3.1.13 on 2023-03-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230309_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mark',
        ),
    ]
