# Generated by Django 3.1.13 on 2023-03-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_question_pub_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Calculation',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='question_text',
            new_name='question',
        ),
    ]
